### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by Awe1alex** [Awe1alex/concentration-game#1]
Game Fixes: 
- [ ] Default color of cards black
- [ ] Active cards are colorized
- [ ] Used cards are colorized, but with less opacity

Visual fixes:
- [ ] Remove unused data
- [ ] Overall visual fixes
- [ ] Add highscore (will be lost when page reloaded :c )
